# Generated by Django 3.0.7 on 2021-06-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20210603_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='other_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_no',
        ),
    ]
