# Generated by Django 3.0.7 on 2021-06-02 07:45

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={'verbose_name_plural': 'Laboratories'},
        ),
        migrations.CreateModel(
            name='TestRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Complete Blood Count', 'Complete Blood Count'), ('Prothrombin Time', 'Prothrombin Time'), ('Basic Metabolic Panel', 'Basic Metabolic Panel'), ('Comprehensive Metabolic Panel', 'Comprehensive Metabolic Panel'), ('Lipid Panel', 'Lipid Panel'), ('Liver Panel', 'Liver Panel'), ('Thyroid Stimulating Hormone', 'Thyroid Stimulating Hormone'), ('Hemoglobin A1C', 'Hemoglobin A1C'), ('Urinalysis', 'Urinalysis'), ('Culture', 'Culture'), ('Thyroid Profile III', 'Thyroid Profile III'), ('Activated Partial Thromboplastin Time', 'Activated Partial Thromboplastin Time'), ('Lipid Profile', 'Lipid Profile')], max_length=100, null=True)),
                ('state', models.CharField(blank=True, choices=[('Ordered', 'Ordered'), ('Draft', 'Draft')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Sample')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.LabTechnician')),
            ],
        ),
    ]
