# Generated by Django 3.0.7 on 2021-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20210602_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequests',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
