# Generated by Django 3.0.7 on 2021-06-03 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_testrequests_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date_completed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='test',
            name='date_initiated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
