# Generated by Django 3.0.7 on 2021-06-03 17:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20210603_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
