# Generated by Django 3.0.7 on 2021-06-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_auto_20210603_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in dollars', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='lower_bound',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='upper_bound',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
