# Generated by Django 3.0.7 on 2021-06-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_sample_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='source',
        ),
    ]
